local: &local
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: deploy
  password: deploy

development:
  <<: *local
  database: geripsy_development

test:
  <<: *local
  database: geripsy_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
